/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author natty
 */
public class CrearApoderado extends javax.swing.JFrame {

    /**
     * Creates new form CrearApoderadi
     */
    public CrearApoderado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbltTitulo = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        casillaNombre = new javax.swing.JTextField();
        jLblRut = new javax.swing.JLabel();
        casillaRut = new javax.swing.JTextField();
        jLblDireccion = new javax.swing.JLabel();
        casillaDireccion = new javax.swing.JTextField();
        jLblNumero = new javax.swing.JLabel();
        casillaNumero = new javax.swing.JTextField();
        jLblParentesco = new javax.swing.JLabel();
        ComboBoxParentesco = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(472, 651));

        jLbltTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLbltTitulo.setForeground(new java.awt.Color(0, 130, 130));
        jLbltTitulo.setText("NUEVO APODERADO");

        jLblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblNombre.setForeground(new java.awt.Color(0, 130, 130));
        jLblNombre.setText("Nombre y apellido:");

        jLblRut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblRut.setForeground(new java.awt.Color(0, 130, 130));
        jLblRut.setText("Rut (sin guión y dígito verificador):");

        casillaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaRutActionPerformed(evt);
            }
        });

        jLblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblDireccion.setForeground(new java.awt.Color(0, 130, 130));
        jLblDireccion.setText("Dirección:");

        jLblNumero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblNumero.setForeground(new java.awt.Color(0, 130, 130));
        jLblNumero.setText("Numero de contacto:");

        jLblParentesco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblParentesco.setForeground(new java.awt.Color(0, 130, 130));
        jLblParentesco.setText("Parentesco:");

        ComboBoxParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hijo", "Nieto", "Bisnieto", "Otro" }));

        btnRegistrar.setBackground(new java.awt.Color(0, 130, 130));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 130, 130));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLbltTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNombre)
                            .addComponent(jLblRut)
                            .addComponent(jLblDireccion)
                            .addComponent(casillaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(casillaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casillaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLblNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(casillaNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblParentesco)
                                        .addComponent(ComboBoxParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(22, 22, 22)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btnRegistrar)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addGap(38, 38, 38)
                .addComponent(jLbltTitulo)
                .addGap(56, 56, 56)
                .addComponent(jLblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casillaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casillaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casillaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumero)
                    .addComponent(jLblParentesco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casillaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnRegistrar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        // TODO add your handling code here:
        Menu atras=new Menu();
        atras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void casillaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casillaRutActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        int numeroInt=0;
        boolean error=false;
        
        Modelos.Main principal=new Modelos.Main();
        
        Modelos.AdultoMayor adultos=null;
        
        String rut=casillaRut.getText();
        String nombre=casillaNombre.getText();
        String direccion=casillaDireccion.getText();
        
        String numeroContacto=casillaNumero.getText();
        try{
            numeroInt=Integer.parseInt(numeroContacto);
        }catch(NumberFormatException ex){
            ex.printStackTrace();
        }
        
        String parentesco=(String) ComboBoxParentesco.getSelectedItem();
        
        //falta sacarle el color si modifica el dato por uno valido
        if (!rut.matches("[0-9]*")){
            casillaRut.setBackground(new Color(250, 108, 97));
            error=true;
        }if (!nombre.matches("[a-zA-Z]*")){
            casillaNombre.setBackground(new Color(250, 108, 97));
            error=true;
        }else if (!direccion.matches("[a-zA-Z]*")){
            casillaDireccion.setBackground(new Color(250, 108, 97));
            error=true;
        }else if (!numeroContacto.matches("[0-9]*")){
            casillaNumero.setBackground(new Color(250, 108, 97));
            error=true;
        }
        
        if (error!=true){
            adultos.agregarApoderado(rut, nombre, direccion, parentesco, numeroInt);
            //principal.crearAdulto(adultos);

            JOptionPane.showMessageDialog(this, "Persona a cargo registrada");
            Menu registrada=new Menu();
            registrada.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearApoderado().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxParentesco;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField casillaDireccion;
    private javax.swing.JTextField casillaNombre;
    private javax.swing.JTextField casillaNumero;
    private javax.swing.JTextField casillaRut;
    private javax.swing.JLabel jLblDireccion;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JLabel jLblParentesco;
    private javax.swing.JLabel jLblRut;
    private javax.swing.JLabel jLbltTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
